### PR TITLE
Fixing typo for go mod support

### PR DESCRIPTION
**Pull request by helloworldpark**
1. Fixed one left ```github.com/Sirupsen/logrus``` -> ```github.com/sirupsen/logrus```
2. Added ```.gitignore```

### CODE REVIEW

**Comment by struCoder** [comment]
@helloworldpark 
Thanks for your commits.
In beta branch, has supported go module.

**Comment by helloworldpark** [comment]
I've checked that. The commit I suggested is about a minor fix. There was one left typo.

**Comment by helloworldpark** [comment]
Maybe changing the title of the PR would be better for understanding

**Comment by struCoder** [comment]
@helloworldpark 
merged. 
Thanks. :）

**Pull request merged**
